CREATE DATABASE GAME_DB_DEV;
--CREATE DATABASE GAME_DB_TEST;
--CREATE DATABASE GAME_DB_PROD;

USE GAME_DB_DEV;

CREATE TABLE USER(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150)
);

CREATE TABLE MONSTER(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150)
);

CREATE TABLE COLLECTED_COIN(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    VALUE_COIN INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE KILLED_MONSTER(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    MONSTER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (MONSTER_ID) REFERENCES MONSTER(ID)
);

CREATE TABLE DEATHS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TIME_REG TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE TROPHY(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(45)
);

CREATE TABLE USER_TROPHY(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TROPHY_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (TROPHY_ID) REFERENCES TROPHY(ID)
);



INSERT INTO USERS VALUES (0, 'noob_master123');
INSERT INTO USERS VALUES (1, 'isa_tocadocoelho');

INSERT INTO MONSTER VALUES (0, 'Turtle');
INSERT INTO MONSTER VALUES (1, 'Bowser');

INSERT INTO TROPHY VALUES (0, 'OURO');
INSERT INTO TROPHY VALUES (1, 'PRATA');
INSERT INTO TROPHY VALUES (2, 'BRONZE');
INSERT INTO TROPHY VALUES (3, 'LATAO');
INSERT INTO TROPHY VALUES (5, 'MADEIRA');

INSERT INTO COLLECTED_COIN VALUES (0, 0, 1);
INSERT INTO COLLECTED_COIN VALUES (1, 0, 2);
INSERT INTO COLLECTED_COIN VALUES (2, 0, 5);
INSERT INTO COLLECTED_COIN VALUES (3, 0, 2);

INSERT INTO COLLECTED_COIN VALUES (5, 1, 1);
INSERT INTO COLLECTED_COIN VALUES (6, 1, 2);
INSERT INTO COLLECTED_COIN VALUES (7, 1, 5);
INSERT INTO COLLECTED_COIN VALUES (8, 1, 2);

INSERT INTO KILLED_MONSTER VALUES (0, 0, 1);
INSERT INTO KILLED_MONSTER VALUES (1, 0, 2);
INSERT INTO KILLED_MONSTER VALUES (2, 0, 1);
INSERT INTO KILLED_MONSTER VALUES (3, 0, 2);

INSERT INTO KILLED_MONSTER VALUES (5, 1, 1);
INSERT INTO KILLED_MONSTER VALUES (6, 1, 2);
INSERT INTO KILLED_MONSTER VALUES (7, 1, 2);
INSERT INTO KILLED_MONSTER VALUES (8, 1, 2);

INSERT INTO DEATHS VALUES (0, 0, SYSDATE());
SELECT SLEEP(3);
INSERT INTO DEATHS VALUES (1, 0, SYSDATE());
SELECT SLEEP(3);
INSERT INTO DEATHS VALUES (2, 1, SYSDATE());

INSERT INTO USER_TROPHY VALUES (0, 0, 1);
INSERT INTO USER_TROPHY VALUES (1, 1, 3);
